baseURL: https://pfp.works/
languageCode: en-us
title: "PfP: Pain-free Passwords"
disableKinds:
  - RSS
  - taxonomyTerm
enableRobotsTXT: true

menu:
  main:
    - Name: Home
      URL: /
      Weight: 1
    - Name: Try Online
      URL: /webclient/
      Weight: 2
    - Name: Documentation
      URL: /documentation/
      Weight: 3
    - Name: Contributing
      URL: /contributing/
      Weight: 4

markup:
  goldmark:
    extensions:
      linkify: false
    parser:
      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
